# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_bot', '0002_auto_20160624_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(default=b'*', max_length=200),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(default=b'*', max_length=200),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(default=b'*', max_length=200),
        ),
    ]
